"""
Test fixtures and configurations for Django backend tests.
Generated by AI assistant to provide comprehensive test setup.
"""

from io import BytesIO

import pytest
from django.core.files.uploadedfile import SimpleUploadedFile
from PIL import Image


@pytest.fixture
def user_data() -> dict[str, str]:
    """Basic user data for user creation - AI generated fixture"""
    return {"email": "test@example.com", "password": "testpass123"}


@pytest.fixture
def user():
    """Test user instance - AI generated fixture"""
    from django.contrib.auth import get_user_model

    data = user_data()
    return get_user_model().objects.create_user(**data)  # type: ignore[attr-defined]


@pytest.fixture
def fake_image():
    """Generate a fake image for testing uploads - AI generated using Pillow"""
    image = Image.new("RGB", (100, 100), color="red")
    image_io = BytesIO()
    image.save(image_io, format="JPEG")
    image_io.seek(0)

    return SimpleUploadedFile(name="test_image.jpg", content=image_io.getvalue(), content_type="image/jpeg")
